plan_gen_prompt="You need to select a proper tool to answer a given question. We have four tools:\n"
plan_gen_prompt+="(A). Reverse image search: The tool aims to find information related to given images, such as the date of, the event in or the celebrities in the image. It uses the provided images as input to query a search engine.\n"
plan_gen_prompt+="(B). Visual question answering: The tool is frequently used for answering questions related to image details (e.g., the text in the image and the weather in the image).\n"
plan_gen_prompt+="(C). Searching Google using texts for textual information: The tool aims to find related textual information by querying a search engine with texts.\n"
plan_gen_prompt+="(D). Searching Google using texts for images: The tool aims to find related images by querying a search engine with texts."
plan_gen_prompt+="You need to response with the options for tools (i.e., A, B, C or D) and please do not respond with any other words. For text-related questions, please select from tool C and D. For image-related questions, please select from A and B.\n\nBelow we provide some examples:\n"
plan_gen_prompt+="Question: When was the image taken? Image index: 1. Question type: Image-related Tool option: A\n"
plan_gen_prompt+="Question: When was Ilhan Omar born? Question type: Text-related Tool option: C\n"
plan_gen_prompt+="Question: Are the person in the two images the same person? Image index: 1,3. Question type: Image-related Tool option: B\n"
plan_gen_prompt+="Question: Any picture for Bonifacio Global City in Philippine? Question type: Text-related Tool option: D\n"
plan_gen_prompt+="Question: What kind of missiles did Iran fire on a US base in 2020? Question type: Text-related Tool option: C\n"
plan_gen_prompt+="Question: What type of missiles are shown in the image? Image index: 3. Question type: Image-related Tool option: A\n"
plan_gen_prompt+="Question: Did Prince Philip pretend to be the palace guard? Question type: Text-related Tool option: D\n"
plan_gen_prompt+="Question: What is the definition of Black or African American? Question type: Text-related Tool option: C\n"
plan_gen_prompt+="Question: What is the text on the board in the image? Image index: 1. Question type: Image-related Tool option: B\n"
plan_gen_prompt+="\n\nQuestion: %s Question type: %s Tool option:"


plan_gen_prompt_icl="You need to select a proper tool to answer a given question. We have four tools:\n"
plan_gen_prompt_icl+="(A). Reverse image search: The tool aims to find information related to given images, such as the date of, the event in or the celebrities in the image. It uses the provided images as input to query a search engine.\n"
plan_gen_prompt_icl+="(B). Visual question answering: The tool is frequently used for answering questions related to image details (e.g., the text in the image and the weather in the image).\n"
plan_gen_prompt_icl+="(C). Searching Google using texts for textual information: The tool aims to find related textual information by querying a search engine with texts.\n"
plan_gen_prompt_icl+="(D). Searching Google using texts for images: The tool aims to find related images by querying a search engine with texts."
plan_gen_prompt_icl+="You need to response with the options for tools (i.e., A, B, C or D) and please do not respond with any other words. For text-related questions, please select from tool C and D. For image-related questions, please select from A and B.\n\nBelow we provide some examples:"